plugins {
    id 'java'
    id("io.freefair.lombok") version "9.5.0"
}

group = 'eu.senla.regoffice'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation("org.seleniumhq.selenium:selenium-java:4.46.0")
    implementation("net.datafaker:datafaker:2.7.0")

    implementation("io.rest-assured:rest-assured:6.0.1")

    implementation("tools.jackson.core:jackson-databind:3.2.2")

    implementation("io.qameta.allure:allure-rest-assured:2.35.4")
    implementation("io.qameta.allure:allure-junit5:2.35.4")
}

test {
    useJUnitPlatform()
}